add redundancy

diff --git a/commands/configure-service b/commands/configure-service
--- a/commands/configure-service
+++ b/commands/configure-service
@@ -178,7 +178,21 @@ if [[ "$launchConfigurationExists" = false ]]; then
     echo "---- No launch configuration $AUTO_SCALING_GROUP_NAME exists, creating!"
     securityGroupId=$( aws ec2 describe-security-groups --group-names "$SECURITY_GROUP_NAME" | jq -r '.SecurityGroups | .[0] | .GroupId' )
     applicationSecurityGroupId=$( aws ec2 describe-security-groups --group-names "$APPLICATION_SECURITY_GROUP_NAME" | jq -r '.SecurityGroups | .[0] | .GroupId' )
-    aws autoscaling create-launch-configuration --launch-configuration-name "$AUTO_SCALING_GROUP_NAME" --image-id "ami-5ec1673e" --instance-type t2.micro --key-name "$EC2_KEYPAIR_NAME" --security-groups "$securityGroupId" "$applicationSecurityGroupId" --iam-instance-profile "$EC2_IAM_PROFILE_NAME" --user-data "file://$serviceRoot/aws.config/ec2bootstrap.sh"
+    # Unfortuantely, the create-launch-configuration call can sometimes fail sporadically
+    set +e
+    for x in $( seq 1 3 ); do
+	aws autoscaling create-launch-configuration --launch-configuration-name "$AUTO_SCALING_GROUP_NAME" --image-id "ami-5ec1673e" --instance-type t2.micro --key-name "$EC2_KEYPAIR_NAME" --security-groups "$securityGroupId" "$applicationSecurityGroupId" --iam-instance-profile "$EC2_IAM_PROFILE_NAME" --user-data "file://$serviceRoot/aws.config/ec2bootstrap.sh"
+	if [[ $? -eq 0 ]]; then
+	    break
+	fi
+	
+	if [[ $x -eq 3 ]]; then
+	    echo "---- Unable to create launch configuration!! Please check or attempt manually"
+	    exit 1
+	fi
+	echo "---- Re-attempting to create launch configuration"
+    done
+    set -e
 else
     echo "---- Launch configuration $AUTO_SCALING_GROUP_NAME already exists!"
 fi
diff --git a/commands/delete-service b/commands/delete-service
--- a/commands/delete-service
+++ b/commands/delete-service
@@ -146,11 +146,23 @@ fi
 #######################################################
 echo "-- Verifying all resources released"
 
-autoScalingGroupExists="$( aws autoscaling describe-auto-scaling-groups | jq '.AutoScalingGroups | any(.AutoScalingGroupName == "'"$AUTO_SCALING_GROUP_NAME"'")' )"
-if [[ "$autoScalingGroupExists" = "true" ]]; then
-    echo "---- Failed to delete auto scaling group $AUTO_SCALING_GROUP_NAME"
-    exit -1
-fi
+set +e
+for x in $( seq 1 3 ); do
+    autoScalingGroupExists="$( aws autoscaling describe-auto-scaling-groups | jq '.AutoScalingGroups | any(.AutoScalingGroupName == "'"$AUTO_SCALING_GROUP_NAME"'")' )"
+    if [[ "$autoScalingGroupExists" = "false" ]]; then
+	break
+    fi
+    
+    if [[ $x -eq 3 ]]; then
+	echo "---- Failed to delete auto scaling group $AUTO_SCALING_GROUP_NAME"
+	exit 1
+    fi
+    
+    echo "---- Re-checking if auto scaling group was deleted"
+done
+
+
+set -e
 
 launchConfigurationExists="$( aws autoscaling describe-launch-configurations | jq '.LaunchConfigurations | any(.LaunchConfigurationGroupName == "'"$AUTO_SCALING_GROUP_NAME"'")' )"
 if [[ "$launchConfigurationExists" = "true" ]]; then
